## Install the xlogit library

In [1]:
# !pip install xlogit
from xlogit.mixed_logit import MixedLogit
from xlogit.multinomial_logit import MultinomialLogit


## Electricity Dataset¶


### Read Data

In [8]:
# import pandas as pd
# import numpy as np
# df = pd.read_csv("https://raw.githubusercontent.com/arteagac/xlogit/master/examples/data/electricity_long.csv")

# varnames = ["pf", "cl", "loc", "wk", "tod", "seas"]
# transvars = ["pf", "loc", "tod"]
# X = df[varnames].values
# y = df['choice'].values
# alt =[1, 2, 3, 4]

### Fit the model

In [10]:
# # from xlogit import MixedLogit

# model = MixedLogit()
# model.fit(X, y, 
#           varnames, 
#           alt=alt, 
#           transvars=transvars,
#           randvars={'pf': 'n','cl':'n','loc':'n','wk':'n','tod':'n','seas':'n'}, 
# #           mixby=df.id.values,
#           n_draws = 600)
# model.summary()

## Fishing Dataset

### Read Data

In [4]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/arteagac/xlogit/master/examples/data/fishing_long.csv")

varnames = ['price','catch']
X = df[varnames].values
y = df['choice'].values
transvars = ['price', 'catch']


### Fit the model

In [5]:
# from xlogit import MixedLogit

model = MixedLogit()
model.fit(X, y, alt=['beach', 'boat', 'charter', 'pier'],   # bcvars=bcvars,
          # isvars=['income'],  # , asvars=['price'],
          # asvars=asvars,
          transvars=transvars, 
          transformation="boxcox",
          randvars={'price': 'n', 'catch': 'n'},
          varnames=varnames,  # init_coeff=[0],#init_coeff=np.zeros(X.shape[1])
          # fit_intercept=True
          )
model.summary()

testryan2 fit False transformation boxcox
hashasts
isvars []
asvars []
randtranspos [0, 1]
Kf 0 Kr 0 Kftrans 0 Krtrans 2
xrtranshere [[1.57930e+02 6.78000e-02]
 [1.57930e+02 2.60100e-01]
 [1.82930e+02 5.39100e-01]
 ...
 [2.35436e+02 6.81700e-01]
 [2.60436e+02 2.30140e+00]
 [3.39890e+02 1.49800e-01]]
self.asvars [] self.isvars []
Kf 0 Kr 0 Kft 0 Krt 2
postfinalmat [[[[1.57930e+02 6.78000e-02]
   [1.57930e+02 2.60100e-01]
   [1.82930e+02 5.39100e-01]
   [1.57930e+02 5.03000e-02]]]


 [[[1.51140e+01 1.04900e-01]
   [1.05340e+01 1.57400e-01]
   [3.45340e+01 4.67100e-01]
   [1.51140e+01 4.51000e-02]]]


 [[[1.61874e+02 5.33300e-01]
   [2.43340e+01 2.41300e-01]
   [5.93340e+01 1.02660e+00]
   [1.61874e+02 4.52200e-01]]]


 ...


 [[[6.50360e+01 5.33300e-01]
   [1.08546e+02 2.41300e-01]
   [1.43546e+02 1.02660e+00]
   [6.50360e+01 4.52200e-01]]]


 [[[3.66360e+01 5.33300e-01]
   [6.11460e+01 1.66500e-01]
   [9.61460e+01 3.97500e-01]
   [3.66360e+01 4.52200e-01]]]


 [[[3.39890e+02 2.53700e-01

pch [[[0.31576031 0.31496826 0.31164871 ... 0.31190711 0.31270377 0.31683392]]

 [[0.18243132 0.18639322 0.17264121 ... 0.17327316 0.17781859 0.1788296 ]]

 [[0.45852867 0.45439419 0.45529575 ... 0.43906443 0.45182962 0.44384339]]

 ...

 [[0.30545215 0.3052339  0.30701216 ... 0.30595933 0.30633197 0.30686785]]

 [[0.35250563 0.35246993 0.34971452 ... 0.34826056 0.3501971  0.35120088]]

 [[0.29457792 0.29344678 0.29408515 ... 0.29353505 0.29315163 0.29419059]]] 2 [[[0.31279861]]

 [[0.17635711]]

 [[0.45359859]]

 ...

 [[0.30586704]]

 [[0.35082528]]

 [[0.29342927]]]
gnpw [[ 7.72180712e-02  9.69146858e-01  2.80142794e-03  2.74648408e-02
   1.15222156e+00  2.99033394e+00]
 [ 6.97009019e-01  1.10313076e+00  1.99751185e-03  7.16226571e-02
   1.20401607e+01  3.40633051e+00]
 [-5.83707267e-01 -5.85873460e-01 -2.80278429e-02 -9.01575507e-03
  -9.49266362e+00 -1.91962205e+00]
 ...
 [-1.96228263e-01 -1.13716991e-01 -3.61680837e-02 -9.25521726e-03
  -3.05936563e+00 -3.99206958e-01]
 [-1.83906

gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.27259241 0.27209661 0.2700007  ... 0.27016578 0.27067485 0.27327741]]

 [[0.14544372 0.14765053 0.13995131 ... 0.14028392 0.14284876 0.14339823]]

 [[0.52948418 0.52672682 0.52732751 ... 0.51686574 0.52511641 0.5200335 ]]

 ...

 [[0.31964756 0.31948149 0.32040319 ... 0.31992506 0.32006009 0.32034761]]

 [[0.34829056 0.34826782 0.34643465 ... 0.34547103 0.34675433 0.34742139]]

 [[0.30391636 0.30465958 0.30484886 ... 0.30477219 0.30449651 0.30491988]]] 2 [[[0.27072918]]

 [[0.1420232 ]]

 [[0.52627278]]

 ...

 [[0.31987171]]

 [[0.34717429]]

 [[0.30459179]]]
gnpw [[ 9.83634791e-02  1.15627118e+00  3.57722863e-03  3.29841928e-02
   5.54348354e+00  6.61679918e+00]
 [ 8.04608238e-01  1.26514226e+00  1.44388733e-03  7.74743271e-02
   4.71199477e+01  7.25679801e+00]
 [-5.78549456e-01 -5.31944933e-01 -2.80286250e-02 -9.09989224e-03
  -3.33302100e+01 -3.10298768e+00]
 ...
 [-2.11998945e-01 

H [[ 3.71307024e+02  2.35801684e+02  1.93942073e+00  4.97202893e+00
   2.15495259e+04  1.36289553e+03]
 [ 2.35801684e+02  1.31195746e+03  2.38672037e+00  5.69469315e+00
   1.36319133e+04  7.27782105e+03]
 [ 1.93942073e+00  2.38672037e+00  4.24274020e+00 -1.82671808e-01
   1.12934821e+02  1.36282435e+01]
 [ 4.97202893e+00  5.69469315e+00 -1.82671808e-01  1.41470993e+01
   2.88417108e+02  3.95307078e+01]
 [ 2.15495259e+04  1.36319133e+04  1.12934821e+02  2.88417108e+02
   1.25088269e+06  7.88095477e+04]
 [ 1.36289553e+03  7.27782105e+03  1.36282435e+01  3.95307078e+01
   7.88095477e+04  4.04260060e+04]] (6, 6) g 1182
HinvH [[ 1.59845000e+01 -1.88568795e-01  2.49769321e-02 -1.74735703e-02
  -2.75318528e-01  3.17925387e-02]
 [-1.88568795e-01  7.48852161e-01  7.27299740e-03  7.01043629e-02
   3.61221960e-03 -1.35570163e-01]
 [ 2.49769321e-02  7.27299740e-03  2.36626697e-01  4.25604162e-03
  -4.45817586e-04 -1.36622180e-03]
 [-1.74735703e-02  7.01043629e-02  4.25604162e-03  7.77015686e-02
  

self.Xr_trans (1182, 1, 4, 2)
Xdims (1182, 1, 4, 2)
i -1
i 0
Xrtrans_lmda (1182, 1, 4, 2)
Brtrans (1182, 2, 100)
Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d47d97c0>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.27273711 0.27224034 0.27014033 ... 0.27030574 0.2708158  0.27342345]]

 [[0.14555912 0.14777122 0.1400537  ... 0.14038723 0.14295807 0.14350895]]

 [[0.52924778 0.52648532 0.52708712 ... 0.51660535 0.52487176 0.51977901]]

 ...

 [[0.31960286 0.31943655 0.3203607  ... 0.31988104 0.32001665 0.3203049 ]]

 [[0.34830564 0.34828286 0.34644653 ... 0.34548123 0.34676679 0.347435  ]]

 [[0.30389192 0.30463185 0.30482219 ... 0.30474449 0.30446839 0.30489334]]] 2 [[[0.27087024]]

 [[0.14213058]]

 [[0.5260303 ]]

 ...

 [[0.31982757]]

 [[0.34718744]]

 [[0.30456411]]]
gnpw [[ 9.82875578e-02  1.15560139e+00  3.57443125e-03  3.29675624e-02
   5.499303

Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.27273711 0.27224034 0.27014033 ... 0.27030574 0.2708158  0.27342345]]

 [[0.14555912 0.14777122 0.1400537  ... 0.14038723 0.14295807 0.14350895]]

 [[0.52924778 0.52648532 0.52708712 ... 0.51660535 0.52487176 0.51977901]]

 ...

 [[0.31960286 0.31943655 0.3203607  ... 0.31988104 0.32001665 0.3203049 ]]

 [[0.34830564 0.34828286 0.34644653 ... 0.34548123 0.34676679 0.347435  ]]

 [[0.30389192 0.30463185 0.30482219 ... 0.30474449 0.30446839 0.30489334]]] 2 [[[0.27087024]]

 [[0.14213058]]

 [[0.5260303 ]]

 ...

 [[0.31982757]]

 [[0.34718744]]

 [[0.30456411]]]
gnpw [[ 9.82875578e-02  1.15560139e+00  3.57443125e-03  3.29675624e-02
   5.49930353e+00  6.58515192e+00]
 [ 8.04247982e-01  1.26458421e+00  1.44683301e-03  7.74591726e-02
   4.67727509e+01  7.22306078e+00]
 [-5.78602815e-01 -5.32137094e-01 -2.80309419e-02 -9.10196438e-03
  -3.30985746e+01 -3.09146642e+00]
 

gnpw [[ 9.82875578e-02  1.15560139e+00  3.57443125e-03  3.29675624e-02
   5.49930353e+00  6.58515192e+00]
 [ 8.04247982e-01  1.26458421e+00  1.44683301e-03  7.74591726e-02
   4.67727509e+01  7.22306078e+00]
 [-5.78602815e-01 -5.32137094e-01 -2.80309419e-02 -9.10196438e-03
  -3.30985746e+01 -3.09146642e+00]
 ...
 [-2.11948077e-01 -8.28618672e-02 -3.90370945e-02 -6.46323850e-03
  -1.19896652e+01 -4.97489170e-01]
 [-2.06899467e-01  2.97180470e-01  6.58130781e-03 -4.18118943e-02
  -1.18272821e+01  1.69354674e+00]
 [-1.51642629e-01  3.09195283e-02 -6.08196880e-03 -1.79232648e-02
  -8.40811648e+00  9.73642317e-02]]
g.t. [[ 9.82875578e-02  8.04247982e-01 -5.78602815e-01 ... -2.11948077e-01
  -2.06899467e-01 -1.51642629e-01]
 [ 1.15560139e+00  1.26458421e+00 -5.32137094e-01 ... -8.28618672e-02
   2.97180470e-01  3.09195283e-02]
 [ 3.57443125e-03  1.44683301e-03 -2.80309419e-02 ... -3.90370945e-02
   6.58130781e-03 -6.08196880e-03]
 [ 3.29675624e-02  7.74591726e-02 -9.10196438e-03 ... -6.463238

betas [-1.02703392  0.29588509  0.00659455  0.01977939 -0.06100923  0.07844697]
Brtrans_b [-1.02703392  0.29588509] Brtrans_w [0.00659455 0.01977939] rlmda [-0.06100923  0.07844697]
 self.P 1
self.Kf 0
self.Xr_trans (1182, 1, 4, 2)
Xdims (1182, 1, 4, 2)
i -1
i 0
Xrtrans_lmda (1182, 1, 4, 2)
Brtrans (1182, 2, 100)
Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d47d77c0>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.31843615 0.31761599 0.31421514 ... 0.31447612 0.31528042 0.31952192]]

 [[0.18688961 0.19098454 0.17677035 ... 0.17737972 0.18209609 0.18310993]]

 [[0.44815618 0.44403228 0.44493211 ... 0.42848994 0.44140731 0.43327887]]

 ...

 [[0.30288858 0.30267741 0.30449948 ... 0.3034048  0.30380025 0.30434708]]

 [[0.35078076 0.35074889 0.3479201  ... 0.34643882 0.34840905 0.34943849]]

 [[0.29273902 0.2915492  0.29218912 ... 0.29163185 0.29125819 0.29

rpdist ['price', 'catch'] <enumerate object at 0x7fd7d4793c00>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.3086077  0.30786555 0.30474844 ... 0.30499179 0.30574211 0.30961857]]

 [[0.17593268 0.17957975 0.16691194 ... 0.16749178 0.17168227 0.17261159]]

 [[0.47033218 0.4664031  0.46725969 ... 0.45194648 0.46399703 0.45648219]]

 ...

 [[0.30793611 0.30772369 0.30934128 ... 0.30840133 0.30872506 0.30921507]]

 [[0.35184403 0.35181006 0.34920595 ... 0.34783156 0.34966234 0.35061094]]

 [[0.29643761 0.29574712 0.29629152 ... 0.2958442  0.29547635 0.29639147]]] 2 [[[0.30582935]]

 [[0.17033452]]

 [[0.46567069]]

 ...

 [[0.3083159 ]]

 [[0.35025577]]

 [[0.29571602]]]
gnpw [[ 8.05248545e-02  9.98503609e-01  2.92233056e-03  2.84322078e-02
   1.41544274e+00  3.27713534e+00]
 [ 7.14879678e-01  1.12945934e+00  1.94779342e-03  7.27658621e-02
   1.42306515e+01  3.71108181e+00]
 [-5.84404804e-01 -5.77448846e-01 -2.81

self.Xr_trans (1182, 1, 4, 2)
Xdims (1182, 1, 4, 2)
i -1
i 0
Xrtrans_lmda (1182, 1, 4, 2)
Brtrans (1182, 2, 100)
Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d478a4c0>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.415469

Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71109498e+00]
 [-5.84405014e-01 -5.77448212e-01 -2.81246431e-02 -9.13409878e-03
  -1.10481801e+01 -1.99856997e+00]
 

rpdist ['price', 'catch'] <enumerate object at 0x7fd7d47daa40>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71109498e+00]
 [-5.84405014e-01 -5.77448212e-01 -2.81

gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71109498e+00]
 [-5.84405014e-01 -5.77448212e-01 -2.81246431e-02 -9.13409878e-03
  -1.10481801e+01 -1.99856997e+00]
 ...
 [-1.98942560e-01 

gfinal [ -28.38223291  -63.88018487    1.090298      4.06873421 -378.40795978
  -74.0757466 ]
betas [-1.0239157   0.26597015  0.00599096  0.01803687 -0.04602439  0.06813322]
Brtrans_b [-1.0239157   0.26597015] Brtrans_w [0.00599096 0.01803687] rlmda [-0.04602439  0.06813322]
 self.P 1
self.Kf 0
self.Xr_trans (1182, 1, 4, 2)
Xdims (1182, 1, 4, 2)
i -1
i 0
Xrtrans_lmda (1182, 1, 4, 2)
Brtrans (1182, 2, 100)
Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d47aea40>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.347831

Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d47d9400>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71

rpdist ['price', 'catch'] <enumerate object at 0x7fd7d4793c00>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71109498e+00]
 [-5.84405014e-01 -5.77448212e-01 -2.81

pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71109498e+00]
 [-5.84405014e-01 -5.77448212e-01 -2.81246431e-02 -9.13409878e-03
  -1.10481801e+01 -1.99856997e+00]
 ...
 [-1.98942560e-01 -1.08406200e-01 -3.66661858e-02 -8.78320112e-03
  -3.62883353e+00 -3.99987541e-01]
 [-1.87736

betas [-1.0239157   0.26597015  0.00599096  0.01803687 -0.04602439  0.06813322]
Brtrans_b [-1.0239157   0.26597015] Brtrans_w [0.00599096 0.01803687] rlmda [-0.04602439  0.06813322]
 self.P 1
self.Kf 0
self.Xr_trans (1182, 1, 4, 2)
Xdims (1182, 1, 4, 2)
i -1
i 0
Xrtrans_lmda (1182, 1, 4, 2)
Brtrans (1182, 2, 100)
Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d47d9400>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29

HinvH [[ 1.92208917e+00 -3.92186795e-02  1.65903416e-02 -8.08183033e-03
  -9.69805354e-02  1.05919196e-02]
 [-3.92186795e-02  1.02547310e-01  2.02496532e-03  1.56934535e-02
   2.34746706e-03 -3.36422541e-02]
 [ 1.65903416e-02  2.02496532e-03  2.82406087e-01  6.16583781e-03
  -9.01406507e-04 -7.23109943e-04]
 [-8.08183033e-03  1.56934535e-02  6.16583781e-03  8.85370369e-02
   3.93167504e-04 -5.09425762e-03]
 [-9.69805354e-02  2.34746706e-03 -9.01406507e-04  3.93167504e-04
   4.90434057e-03 -6.68671354e-04]
 [ 1.05919196e-02 -3.36422541e-02 -7.23109943e-04 -5.09425762e-03
  -6.68671354e-04  1.11538609e-02]]
gfinal [ -28.38223291  -63.88018487    1.090298      4.06873421 -378.40795978
  -74.0757466 ]
betas [-1.0239157   0.26597015  0.00599096  0.01803687 -0.04602439  0.06813322]
Brtrans_b [-1.0239157   0.26597015] Brtrans_w [0.00599096 0.01803687] rlmda [-0.04602439  0.06813322]
 self.P 1
self.Kf 0
self.Xr_trans (1182, 1, 4, 2)
Xdims (1182, 1, 4, 2)
i -1
i 0
Xrtrans_lmda (1182, 1, 4, 2)
B

rpdist ['price', 'catch'] <enumerate object at 0x7fd7d3e09900>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71109498e+00]
 [-5.84405014e-01 -5.77448212e-01 -2.81

rpdist ['price', 'catch'] <enumerate object at 0x7fd7d4615700>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71109498e+00]
 [-5.84405014e-01 -5.77448212e-01 -2.81

Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71109498e+00]
 [-5.84405014e-01 -5.77448212e-01 -2.81246431e-02 -9.13409878e-03
  -1.10481801e+01 -1.99856997e+00]
 

Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00  1.94779504e-03  7.27659169e-02
   1.42308741e+01  3.71109498e+00]
 [-5.84405014e-01 -5.77448212e-01 -2.81246431e-02 -9.13409878e-03
  -1.10481801e+01 -1.99856997e+00]
 

i 0
Xrtrans_lmda (1182, 1, 4, 2)
Brtrans (1182, 2, 100)
Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d3e09900>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860734 0.30786518 0.30474808 ... 0.30499144 0.30574175 0.30961819]]

 [[0.17593228 0.17957933 0.16691157 ... 0.16749141 0.17168188 0.1726112 ]]

 [[0.47033302 0.46640394 0.46726053 ... 0.45194737 0.46399789 0.45648308]]

 ...

 [[0.3079363  0.30772388 0.30934147 ... 0.30840152 0.30872525 0.30921525]]

 [[0.35184407 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061099]]

 [[0.29643775 0.29574728 0.29629167 ... 0.29584436 0.2954765  0.29639162]]] 2 [[[0.30582899]]

 [[0.17033414]]

 [[0.46567154]]

 ...

 [[0.30831609]]

 [[0.35025581]]

 [[0.29571618]]]
gnpw [[ 8.05251259e-02  9.98504981e-01  2.92234049e-03  2.84322528e-02
   1.41546934e+00  3.27714774e+00]
 [ 7.14881196e-01  1.12946061e+00

gfinal [ -32.10877812  -68.72847763    1.06833306    4.07876993 -406.31646484
  -84.47188752]
betas [-1.02405366  0.26729367  0.00601767  0.01811396 -0.04668737  0.06858953]
Brtrans_b [-1.02405366  0.26729367] Brtrans_w [0.00601767 0.01811396] rlmda [-0.04668737  0.06858953]
 self.P 1
self.Kf 0
self.Xr_trans (1182, 1, 4, 2)
Xdims (1182, 1, 4, 2)
i -1
i 0
Xrtrans_lmda (1182, 1, 4, 2)
Brtrans (1182, 2, 100)
Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d2a3ff80>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30904837 0.30830276 0.30517296 ... 0.30541712 0.3061699  0.31006264]]

 [[0.17641521 0.18008195 0.16734622 ... 0.16792756 0.17214106 0.17307423]]

 [[0.46932942 0.46539085 0.46624954 ... 0.45088414 0.46297489 0.45543199]]

 ...

 [[0.30770978 0.30749734 0.30912384 ... 0.30817725 0.30850402 0.30899652]]

 [[0.35179532 0.35176142 0.34914729 ... 0.347768

betas [-1.02391719  0.26598443  0.00599125  0.0180377  -0.04603155  0.06813815]
Brtrans_b [-1.02391719  0.26598443] Brtrans_w [0.00599125 0.0180377 ] rlmda [-0.04603155  0.06813815]
 self.P 1
self.Kf 0
self.Xr_trans (1182, 1, 4, 2)
Xdims (1182, 1, 4, 2)
i -1
i 0
Xrtrans_lmda (1182, 1, 4, 2)
Brtrans (1182, 2, 100)
Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d47e0780>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.3086121  0.30786991 0.30475267 ... 0.30499604 0.30574638 0.309623  ]]

 [[0.17593749 0.17958475 0.16691626 ... 0.16749612 0.17168684 0.1726162 ]]

 [[0.47032217 0.466393   0.46724961 ... 0.45193588 0.46398683 0.45647172]]

 ...

 [[0.30793385 0.30772143 0.30933911 ... 0.3083991  0.30872286 0.30921289]]

 [[0.35184354 0.35180958 0.34920536 ... 0.34783093 0.34966177 0.35061041]]

 [[0.29643596 0.29574527 0.2962897  ... 0.29584234 0.29547448 0.29

betas [-1.02391571  0.2659703   0.00599097  0.01803688 -0.04602447  0.06813328]
Brtrans_b [-1.02391571  0.2659703 ] Brtrans_w [0.00599097 0.01803688] rlmda [-0.04602447  0.06813328]
 self.P 1
self.Kf 0
self.Xr_trans (1182, 1, 4, 2)
Xdims (1182, 1, 4, 2)
i -1
i 0
Xrtrans_lmda (1182, 1, 4, 2)
Brtrans (1182, 2, 100)
Xbr_trans (1182, 1, 4, 100)
VVVV (1182, 1, 4, 100)
rpdist ['price', 'catch'] <enumerate object at 0x7fd7d47e0780>
Xdims (1182, 1, 4, 2)
gradshape (0,) grtrans_b (1182, 2, 100) grtrans_w (1182, 2, 100) grtrans_lmda (1182, 2, 100)
pch [[[0.30860739 0.30786523 0.30474813 ... 0.30499149 0.3057418  0.30961825]]

 [[0.17593234 0.17957938 0.16691162 ... 0.16749147 0.17168193 0.17261125]]

 [[0.4703329  0.46640383 0.46726042 ... 0.45194724 0.46399777 0.45648295]]

 ...

 [[0.30793627 0.30772385 0.30934144 ... 0.3084015  0.30872522 0.30921523]]

 [[0.35184406 0.3518101  0.34920599 ... 0.34783161 0.34966239 0.35061098]]

 [[0.29643773 0.29574726 0.29629165 ... 0.29584434 0.29547648 0.29

gnpw [[ 8.05251241e-02  9.98504971e-01  2.92234043e-03  2.84322525e-02
   1.41546916e+00  3.27714765e+00]
 [ 7.14881185e-01  1.12946060e+00  1.94779503e-03  7.27659165e-02
   1.42308726e+01  3.71109489e+00]
 [-5.84405012e-01 -5.77448216e-01 -2.81246430e-02 -9.13409873e-03
  -1.10481790e+01 -1.99856996e+00]
 ...
 [-1.98942558e-01 -1.08406202e-01 -3.66661854e-02 -8.78320130e-03
  -3.62883313e+00 -3.99987543e-01]
 [-1.87736874e-01  2.75288651e-01  5.88378220e-03 -3.91810383e-02
  -3.53744683e+00  9.25824103e-01]
 [-1.21948598e-01 -9.17058186e-02 -5.02607049e-03 -9.90560892e-03
  -2.07975750e+00 -4.48370470e-01]]
g.t. [[ 8.05251241e-02  7.14881185e-01 -5.84405012e-01 ... -1.98942558e-01
  -1.87736874e-01 -1.21948598e-01]
 [ 9.98504971e-01  1.12946060e+00 -5.77448216e-01 ... -1.08406202e-01
   2.75288651e-01 -9.17058186e-02]
 [ 2.92234043e-03  1.94779503e-03 -2.81246430e-02 ... -3.66661854e-02
   5.88378220e-03 -5.02607049e-03]
 [ 2.84322525e-02  7.27659165e-02 -9.13409873e-03 ... -8.783201

## Car Dataset

### Read Data

In [6]:
# import pandas as pd
# import numpy as np

# df = pd.read_csv("https://raw.githubusercontent.com/arteagac/xlogit/master/examples/data/car100_long.csv")
# df.price = -1*df.price/10000
# df.operating_cost = -1*df.operating_cost

# varnames = ['high_performance','medium_performance','price', 'operating_cost',
#             'range', 'electric', 'hybrid'] 

# X = df[varnames].values
# y = df['choice'].values

### Fit the model

In [7]:

# from xlogit import MixedLogit

# model = MixedLogit()
# model.fit(X, y, varnames = varnames,
#           alt=['car','bus','bike'],
#           randvars = {'price': 'ln', 'operating_cost': 'n',
#                       'range': 'ln', 'electric':'n', 'hybrid': 'n'}, 
#           mixby = df.person_id.values, #Panel column
#           n_draws = 100) 
# model.summary()